name: Sync fork from upstream
on:
  push:
  schedule:
    - cron:  '0 */8 * * *'
jobs:
  sync-from-forked-repo:
    runs-on: self-hosted
    env:
      REPO_NAME: <REPOSITORY-NAME-IN-GITHUB>
      FORK_ORG: <ORG-REPO-IS-FORKED-FROM>
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'fork-sync'
    - name: set upstream url
      run: git remote set-url upstream https://github.devops.topdanmark.cloud/$FORK_ORG/$REPO_NAME || git remote add upstream https://github.devops.topdanmark.cloud/$FORK_ORG/$REPO_NAME
    - name: fetch upstream
      run: git fetch upstream
    - name: rebase
      run: git rebase upstream/main
    - name: set push remote
      run: git remote set-url --push origin https://github.devops.topdanmark.cloud/nlp/$REPO_NAME
    - name: push to nlp repo
      run: git push -f origin fork-sync

  sync-to-azure:
    needs: sync-from-forked-repo
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'fork-sync'
    - name: set azure email
      run: git config --global user.email "azuredevops-am-github-sync@nordeapensiondk.onmicrosoft.com"
    - name: set azure name
      run: git config --global user.name "azuredevops-am-github-sync"
    - name: set remote url
      env:
        AZREPO: <YOUR-AZ-REPO>
        AZPAT: ${{ secrets.AZPAT }}
      run: git remote set-url --push origin https://azuredevops-am-github-sync:$AZPAT@dev.azure.com/nordeapensiondk/Application%20Migration/_git/$AZREPO
    - name: git fetch
      run: git fetch --unshallow origin
    - name: git push
      env:
        AZBRANCH: <YOUR-AZ-BRANCH>
        GITBRANCH: 'fork-sync'
      run: git push origin $GITBRANCH:$AZBRANCH --force
